baseurl      = "https://yevgenypats.github.io/"
title        = "Yevgeny Pats"
languageCode = "en-us"
theme        = "hello-friend-ng"
paginate     = 10

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  # Subtitle for home
  homeSubtitle = "3x Entrepreneur, Software engineer."

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you link
  enableSharingButtons = true

  # Metadata mostly used in document's head
  description = "Yevgeny Pats - Page"
  keywords = "homepage, blog"
  images = [""]

  # Default theme "light" or "dark"
  defaultTheme = "dark"

  [[params.social]]
      name = "twitter"
      url  = "https://twitter.com/yevgenypats"

  [[params.social]]
      name = "linkedin"
      url  = "https://www.linkedin.com/in/yevgeny-pats-5973328b/"

  [[params.social]]
      name = "github"
      url  = "https://github.com/yevgenypats"

[taxonomies]
    category = "categories"
    tag      = "tags"

[languages]
  [languages.en]
    title = "Yevgeny Pats"
    subtitle = "Page"
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "cat ./yevgeny_pats.txt"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
#  [[menu.main]]
#    identifier = "blog"
#    name       = "Blog"
#    url        = "/posts"
